### ISSUE TITLE
Adjust height of text box

### ISSUE THREAD

**Issue by ed-lea** [awt2542/textLayer-for-Framer#1]
Great plugin. I was wondering if you'd ever looked at being able to fix the width of a text layer and make the adjustment in the height of the layer?

**Comment by awt2542** [comment]
thanks! yeah, I just added this. try autoSizeHeight = true in combo with a fixed width. let me know how it works

**Comment by ed-lea** [comment]
I just tried this out this morning and it worked great, didn't get the chance to update the ticket. Nice work :+1:
