### ISSUE TITLE
contentEditable: true breaks when text layer is nested inside a scroll layer

### ISSUE THREAD

**Issue by emmclean** [awt2542/textLayer-for-Framer#10]
When TextLayer t has `t.superLayer = scroll.content` and `contentEditable: true`, the content is not editable. When I remove it from the superLayer, it becomes editable again. Any idea on how to fix this?
Cheers!

**Comment by awt2542** [comment]
Not sure, but contentEditable is usually pretty buggy. A proper input field is usually a better solution for inputs. Try: https://github.com/ajimix/Input-Framer
