### ISSUE TITLE
Getting "TypeError: undefined is not a constructor..." error

### ISSUE THREAD

**Issue by randidumaguet** [awt2542/textLayer-for-Framer#11]
I'm not sure which versions of Framer Studio are affected. I am using v50 (2681).

Fixed by editing line 1 of the module from:
class module.exports extends Layer

to:
class exports.TextLayer extends Layer

[TextLayerError.framer.zip](https://github.com/awt2542/textLayer-for-Framer/files/117018/TextLayerError.framer.zip)
[TextLayerFixed.framer.zip](https://github.com/awt2542/textLayer-for-Framer/files/117019/TextLayerFixed.framer.zip)

**Comment by awt2542** [comment]
Thanks for the example! Made it easier to follow :+1:  This is not really a bug. It depends on how you import/require the plugin. If you use {TextLayer}, then yes - you'll need exports.TextLayer, but if you simply write TextLayer = require... then module.exports should work fine.

**Comment by randidumaguet** [comment]
@awt2542 Ahhhh, that explains it! I guess this should be covered in CoffeeScript 101 Thanks! :+1:
