### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by matthijsotterloo** [awt2542/textLayer-for-Framer#17]
Hi!

Thanks a lot for making this extension! 
I'm using this snippet: 

`t = new TextLayer
    text: "Friend's email"
    color: "#515254"
    fontSize: 12
    width: 220
    height: 40
    y: 150
    x: 40
    contentEditable: true
    fontFamily: "HelveticaNeue"`

Now I'm wanting to execute an action when I start typing, so when I start typing in the textfield another layer will show up, is this possible?

Thanks!

**Comment by awt2542** [comment]
Hi! I'd probably use an input field module for this instead. Try this one: https://github.com/ajimix/Input-Framer

**Comment by matthijsotterloo** [comment]
@awt2542 Thanks! Is this also usable when I'm prototyping for web?

**Comment by matthijsotterloo** [comment]
Solved.
