### ISSUE TITLE
Doens't Work

### ISSUE THREAD

**Issue by mamjed** [awt2542/textLayer-for-Framer#25]
Framer v67 doesn't seem to acknowledge it at a constructor. 

error
`TypeError: Object is not a constructor (evaluating 'new TextLayer')`

**Comment by blaineb** [comment]
Did you try wrapping the require text in a curly bracket?

{TextLayer} = require "TextLayer"

**Comment by mamjed** [comment]
foot in mouth. 

In my defence, I was pretty sure I tried this before.
