### ISSUE TITLE
useful method: replace layer

### ISSUE THREAD

**Issue by johanneseckert** [awt2542/textLayer-for-Framer#6]
it would be great to have a method that allows to replace an existing layer from sketch with a text layer:
- point method to existing layer
- create TextLayer with same superlayer and frame as existing layer
- hide (destroy?) existing layer

the only thing that still has to be set manually are the font attributes.

**Comment by awt2542** [comment]
Good idea! Here's one approach. Let me know what you think:

```
TextLayer = require 'TextLayer'
Layer::frameAsTextLayer = (properties) ->
    t = new TextLayer
    t.frame = @frame
    t.superLayer = @superLayer
    _.extend t,properties
    @destroy()
    t

text = layer.frameAsTextLayer
    fontSize: 12
    color: "black"
```

If you combine it with my Layers module, you can do something like:

```
for layer in Layers.startingWith '_text'
    text = layer.frameAsTextLayer
        fontSize: 12
        color: "black"
        text: layer.name.replace("_text")
```

**Comment by johanneseckert** [comment]
sounds awesome!

**Comment by awt2542** [comment]
I've now added layer.convertToTextLayer() which recreates text and styling as well.
